### ISSUE TITLE
Maven package

### ISSUE THREAD

**Issue by NeoCortex97** [HanSolo/odometer#2]
is this library hosted in a maven repositor, or otherwise has prebuilt jars?
I did not find it anywhere, but I would prefer if it would be to make building my project for a new developer simpler.

And I would like, if you could please add the package info to the readme if possible.

**Comment by HanSolo** [comment]
This is not a library but only one component. If you would like to use it, just fork it and use the code directly.

**Comment by NeoCortex97** [comment]
Okay
